# Crowdin Configuration File
# https://developer.crowdin.com/configuration-file/

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

commit_message: 'chore(i18n): sync translations from Crowdin'
pull_request_title: 'chore(i18n): sync translations from Crowdin'
pull_request_labels:
  - 'documentation :memo:'
  - 'i18n'

files:
  - source: /i18n/locales/en.json
    translation: /i18n/locales/%two_letters_code%.json
  - source: /content/en/**/*.md
    translation: /content/%two_letters_code%/**/%original_file_name%
    content_segmentation: false
