project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: /i18n/locales/en.json
    translation: /i18n/locales/%two_letters_code%.json
  - source: /content/en/**/*.md
    translation: /content/%two_letters_code%/**/%original_file_name%
