import { z } from 'zod'

/** zod schema object for {@link NotificationSchema}. */
export const notificationSchema = z.object({
  /** Auto Generated by Cosmos DB. */
  id: z.ostring(),
  /** Notification sender */
  sender: z.literal('SYSTEM'),
  /** Display on the Top page or not */
  pinned: z.boolean(),
  /** Card color */
  type: z.union([
    z.literal('blue'),
    z.literal('green'),
    z.literal('yellow'),
    z.literal('red'),
  ]),
  /**
   * Icon name
   * https://ui.nuxt.com/components/icon
   */
  icon: z.string().regex(/^i-.+-.+$/),
  title: z.string(),
  body: z.string(),
  timeStamp: z.number(),
})
/**
 * DB schema of "Notification" container
 * @example
 * ```json
 * {
 *   "id": "<Auto Generated>",
 *   "sender": "SYSTEM",
 *   "pinned": true,
 *   "type": "is-info",
 *   "icon": "info",
 *   "title": "このサイトはベータ版です",
 *   "body": "このWebサイトはベータ版環境です。以下の点にご留意してご利用ください。",
 *   "timeStamp": 1597028400
 * }
 * ```
 */
export type NotificationSchema = z.infer<typeof notificationSchema>
