import { z } from 'zod'

/** zod schema object for {@link NotificationSchema}. */
export const notificationSchema = z.object({
  /** Auto Generated by Cosmos DB. */
  id: z.string(),
  /** Card color */
  color: z.union([
    z.literal('blue'),
    z.literal('green'),
    z.literal('yellow'),
    z.literal('red'),
  ]),
  /**
   * Icon name
   * https://ui.nuxt.com/components/icon
   */
  icon: z.string().regex(/^i-.+-.+$/),
  title: z.string(),
  body: z.string(),
  timeStamp: z.number(),
})
/** Site notification */
export type Notification = z.infer<typeof notificationSchema>
