export type NotificationType = 'is-info' | 'is-warning'

/**
 * DB schema of "Notification" container
 * @example
 * ```json
 * {
 *   "id": "<Auto Generated>",
 *   "sender": "SYSTEM",
 *   "pinned": true,
 *   "type": "is-info",
 *   "icon": "info",
 *   "title": "このサイトはベータ版です",
 *   "body": "このWebサイトはベータ版環境です。以下の点にご留意してご利用ください。",
 *   "timeStamp": 1597028400
 * }
 * ```
 */
export type NotificationSchema = {
  /** Auto Generated by Cosmos DB. */
  id: string
  /**
   * Notification sender
   * @description This property is the {@link https://docs.microsoft.com/azure/cosmos-db/partitioning-overview partition key}.
   * @example `"SYSTEM"`: global notification
   */
  sender: 'SYSTEM'
  /** Display on the Top page or not */
  pinned: boolean
  /** style class (like `"is-info"`) */
  type: NotificationType
  /** {@link https://materialdesignicons.com/ Material Design Icon} name */
  icon: string
  /** Notification title */
  title: string
  /** Notification body (Markdown text) */
  body: string
  /** Created time (UNIX time) */
  timeStamp: number
}
