import { calcMaxScore, detectCategory } from '@ddradar/core'

import type {
  DBNotificationSchema,
  DBScoreSchema,
  DBSongSchema,
  DBUserSchema,
} from '../src/schemas'

/** Songs for End to End test. */
export const songs: DBSongSchema[] = [
  {
    id: '8Il6980di8P89lil1PDIqqIbiq1QO8lQ',
    type: 'song',
    name: 'MAKE IT BETTER',
    nameKana: 'MAKE IT BETTER',
    artist: 'mitsu-O!',
    series: 'DDR 1st',
    minBPM: 119,
    maxBPM: 119,
    folders: [],
    charts: [
      {
        playStyle: 1,
        difficulty: 0,
        bpm: [119, 119, 119],
        level: 3,
        notes: 67,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 1,
        bpm: [119, 119, 119],
        level: 7,
        notes: 143,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 2,
        bpm: [119, 119, 119],
        level: 9,
        notes: 188,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 3,
        bpm: [119, 119, 119],
        level: 11,
        notes: 212,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 1,
        bpm: [119, 119, 119],
        level: 7,
        notes: 130,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 2,
        bpm: [119, 119, 119],
        level: 9,
        notes: 181,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 3,
        bpm: [119, 119, 119],
        level: 11,
        notes: 220,
        freezeArrow: 0,
        shockArrow: 0,
      },
    ],
    skillAttackId: 0,
  },
  {
    id: '06loOQ0DQb0DqbOibl6qO81qlIdoP9DI',
    type: 'song',
    name: 'PARANOiA',
    nameKana: 'PARANOIA',
    artist: '180',
    series: 'DDR 1st',
    minBPM: 180,
    maxBPM: 180,
    folders: [],
    charts: [
      {
        playStyle: 1,
        difficulty: 0,
        bpm: [180, 180, 180],
        level: 4,
        notes: 138,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 1,
        bpm: [180, 180, 180],
        level: 8,
        notes: 264,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 2,
        bpm: [180, 180, 180],
        level: 9,
        notes: 275,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 3,
        bpm: [180, 180, 180],
        level: 11,
        notes: 319,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 1,
        bpm: [180, 180, 180],
        level: 8,
        notes: 254,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 2,
        bpm: [180, 180, 180],
        level: 13,
        notes: 309,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 3,
        bpm: [180, 180, 180],
        level: 11,
        notes: 382,
        freezeArrow: 0,
        shockArrow: 0,
      },
    ],
    skillAttackId: 1,
  },
  {
    id: 'Pb9II0oiI9ODQ8OP8IqIPQP9P68biqIi',
    type: 'song',
    name: 'TRIP MACHINE',
    nameKana: 'TRIP MACHINE',
    artist: 'DE-SIRE',
    series: 'DDR 1st',
    minBPM: 160,
    maxBPM: 160,
    folders: [],
    charts: [
      {
        playStyle: 1,
        difficulty: 0,
        bpm: [160, 160, 160],
        level: 3,
        notes: 106,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 1,
        bpm: [160, 160, 160],
        level: 8,
        notes: 191,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 2,
        bpm: [160, 160, 160],
        level: 9,
        notes: 211,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 1,
        difficulty: 3,
        bpm: [160, 160, 160],
        level: 10,
        notes: 230,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 1,
        bpm: [160, 160, 160],
        level: 9,
        notes: 201,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 2,
        bpm: [160, 160, 160],
        level: 10,
        notes: 215,
        freezeArrow: 0,
        shockArrow: 0,
      },
      {
        playStyle: 2,
        difficulty: 3,
        bpm: [160, 160, 160],
        level: 10,
        notes: 264,
        freezeArrow: 0,
        shockArrow: 0,
      },
    ],
    skillAttackId: 2,
  },
]

/** Scores for End to End test. */
export const scores: DBScoreSchema[] = [
  // World Records
  ...songs.flatMap(song =>
    song.charts.map<DBScoreSchema>(chart => ({
      id: `${song.id}/${chart.playStyle}/${chart.difficulty}/0`,
      type: 'score',
      song: {
        id: song.id,
        name: song.name,
        seriesCategory: detectCategory(song.series),
        deleted: song.deleted,
      },
      chart: {
        playStyle: chart.playStyle,
        difficulty: chart.difficulty,
        level: chart.level,
      },
      user: { id: '0', name: '0', area: 0, isPublic: false },
      ...calcMaxScore(chart),
    }))
  ),
]

/** UserData for End to End test. */
export const userData: DBUserSchema[] = [
  {
    id: 'admin_user',
    type: 'user',
    uid: 'admin_user',
    name: '管理者ユーザー',
    loginId: 'ec2c633fcc21433ba087d5fdba4b818a',
    area: 22,
    isPublic: true,
    code: 11173996,
    isAdmin: true,
  },
  {
    id: 'public_user1',
    type: 'user',
    uid: 'public_user',
    name: '一般ユーザー1',
    area: 13,
    isPublic: true,
    loginId: 'ec2c633fcc21433ba087d5fdba4b818b',
  },
  {
    id: 'public_user2',
    type: 'user',
    uid: 'public_user',
    name: '一般ユーザー2',
    area: 0,
    isPublic: true,
    loginId: 'ec2c633fcc21433ba087d5fdba4b818c',
  },
  {
    id: 'private_user',
    type: 'user',
    uid: 'private_user',
    name: '非公開ユーザー',
    area: 13,
    isPublic: false,
    loginId: 'ec2c633fcc21433ba087d5fdba4b818d',
  },
]

/** Notifications for End to End test. */
export const notifications: DBNotificationSchema[] = [
  {
    id: '8bb25185-dfec-40e6-812c-86a016e41ef1',
    type: 'notification',
    sender: 'SYSTEM',
    pinned: true,
    color: 'yellow',
    icon: 'i-heroicons-exclamation-triangle',
    title: 'このサイトはベータ版です',
    body: 'このWebサイトは検証用環境です。 / This site is staging environment.',
    timeStamp: 1596250800,
  },
  {
    id: '05568cb9-e4f1-483c-9e76-f914fc59e0c7',
    type: 'notification',
    sender: 'SYSTEM',
    pinned: false,
    color: 'blue',
    icon: 'i-heroicons-musical-note',
    title: '新曲を追加しました',
    body: '下記の譜面情報を追加しました。\n\n- [新曲](/song/foo)',
    timeStamp: 1597276800,
  },
]
