import type { HttpRequest } from '@azure/functions'

export type ClientPrincipal = {
  identityProvider: 'github' | 'twitter'
  /** Auto generated by Azure Static Web Apps */
  userId: string
  /** User Name (GitHub/Twitter) */
  userDetails: string
  userRoles: string[]
}

export const getClientPrincipal = (
  req: Pick<HttpRequest, 'headers'>
): ClientPrincipal | null => {
  const header = req.headers['x-ms-client-principal']
  if (!header) return null

  try {
    const buffer = Buffer.from(header, 'base64')
    const jsonString = buffer.toString('utf8')
    return JSON.parse(jsonString)
  } catch {
    return null
  }
}
