name: Azure Functions CI/CD

on:
  push:
    branches:
      - main
    paths:
      - core/**
      - db/**
      - functions/**
      - .github/workflows/azure-functions.yml
  release:
    types: [published]

jobs:
  deploy-fa:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event_name == 'release' && 'Production') || 'Staging' }}
      url: ${{ steps.fa-deploy.outputs.app-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Use pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v3.0.0
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        # Workaround for https://github.com/pnpm/pnpm/issues/6166
        run: |
          pnpm build:core
          pnpm -C functions build
          pnpm \
            --filter @ddradar/functions --prod deploy func
            --config.shamefully-hoist=true \
            --config.hoist=true \
            --config.node-linker=true \
            --config.symlinks=false \
            --config.shared-workspace-lockfile=false

      - name: Deploy
        uses: Azure/functions-action@v1.5.1
        id: fa-deploy
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_APP_NAME }}
          slot-name: ${{ vars.AZURE_FUNCTIONAPP_DEPLOY_SLOT }}
          package: ./func
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
