name: Azure Functions CI/CD

on:
  push:
    branches:
      - main
    paths:
      - core/**
      - db/**
      - functions/**
      - .github/workflows/azure-functions.yml
  release:
    types: [published]

jobs:
  deploy-fa:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event_name == 'release' && 'Production') || 'Staging' }}
      url: ${{ steps.fa-deploy.outputs.app-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Use pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm -F "core" build
          pnpm -F "db" build
          pnpm -F "functions" build

      - name: Remove Dev Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Deploy
        uses: Azure/functions-action@v1.5.1
        id: fa-deploy
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_APP_NAME }}
          slot-name: ${{ vars.AZURE_FUNCTIONAPP_DEPLOY_SLOT }}
          package: ./functions
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
