name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - functions/**
      - scripts/**
      - '**.md'
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Use pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: web
          path: web/.output
          include-hidden-files: true

  deploy:
    name: Deploy
    needs: [build]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event_name == 'release' && 'Production') || 'Staging' }}
      url: ${{ steps.swa-deploy.outputs.static_web_app_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: web
          path: web/.output

      - name: Deploy
        id: swa-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          # see: https://aka.ms/swaworkflowconfig
          app_location: 'web/.output/public'
          skip_app_build: true
          api_location: 'web/.output/server'
          skip_api_build: true
          deployment_environment: ${{ vars.AZURE_SWA_DEPLOYMENT_ENVIRONMENT }}
