name: Site Cat LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  post:
    runs-on: ubuntu-latest
    if: (!contains(github.actor, '[bot]'))
    steps:
      - uses: ddradar/lgtm-action@v2.0.0
        with:
          image-url: 'https://user-images.githubusercontent.com/24802730/74030931-9a21ac00-49f3-11ea-872e-374d5bd3e586.jpg'
          search-pattern: |
            ^(lgtm|LGTM)$
            ^@dependabot squash and merge$
