name: Site Cat LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  post:
    runs-on: ubuntu-latest
    if: (!contains(github.actor, '[bot]'))
    steps:
      - uses: ddradar/lgtm-action@v2.0.2
        with:
          image-url: ${{ vars.LGTM_IMAGE_URI }}
          search-pattern: ${{ vars.LGTM_SEARCH_PATTERN }}
