name: Node.js CI (develop)

on:
  push:
    branches:
      - 'develop/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'develop/**'
    paths-ignore:
      - '**.md'

env:
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: yarn lint

  test:
    name: Unit Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./core/coverage/coverage-final.json,./db/coverage/coverage-final.json,./functions/coverage/coverage-final.json
