name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # commit for caching support
        with:
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with: &setup-node-with
          node-version: 24.x

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint:eslint
      - name: Run Prettier
        run: pnpm lint:prettier
        # temporarily disabled until nuxt-hub/core#797 is resolved
      - name: Run vue-tsc (via Nuxt)
        if: false
        run: pnpm lint:typecheck

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # to use OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # commit for caching support
        with:
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with: *setup-node-with

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test --coverage

      - name: Report Code Coverage to codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          use_oidc: true

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: ${{ github.event_name == 'push' && 'production' || 'staging' }}
      url: ${{ vars.ENVIRONMENT == 'production' && 'https://ddradar.app' || steps.deploy.outputs.deployment-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # commit for caching support
        with:
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with: *setup-node-with

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          CLOUDFLARE_ENV: ${{ vars.ENVIRONMENT }}

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: ${{ vars.ENVIRONMENT == 'production' && 'deploy' || format('versions upload --tag pr-{0}', github.event.pull_request.number) }}
