name: Build & Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - functions/**
      - scripts/**
      - '**.md'
  pull_request:
  release:
    types: [published]

env:
  NODE_VERSION: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install Project Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: web
          path: web/.output

  deploy:
    name: Deploy to Azure Static Web Apps
    needs: [build]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-20.04
    environment:
      name: ${{ (github.event_name == 'release' && 'Production') || 'Staging' }}
      url: ${{ steps.swa-deploy.outputs.static_web_app_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Download Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: web
          path: web/.output

      - name: Deploy
        id: swa-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          # see: https://aka.ms/swaworkflowconfig
          app_location: 'web/.output/public'
          skip_app_build: true
          api_location: 'web/.output/server'
          skip_api_build: true
          config_file_location: /
          deployment_environment: ${{ (github.event_name == 'release' && '') || 'beta' }}
